import { aburi, accraZoo, adomi, afadjato, akosombo, anokye, artscenter, bg, bgexplore, bgS, bojo, bosomtwi, bosomtwi1, boti, boti2, bss, bss2, bss41, carpenter, dam, elmina, island, kakum, kakum2, kakum3, kp, kp2, kumasi, KwameNkrumahMausoleum, larabanga, legonGardens, lighthouse, manhyia, mauso, mausoleum, moles, monkey, Nationaltheater, natmauso, natmausoleum, nzulezuEdit, osuCastle, paga, pagaW, shai, slaveRiver, wlifalls } from '../assets/toursites/index.js';
import { ABT, bk, blackStar, ex, forgotcopy, forgotcopyy, forgotlong, Ghana, gif2, map, tour, wallpaper } from '../assets/images/index.js';

const data = [
    {
        id: '2',
        name: 'Elmina Castle',
        description: 'Another historical landmark on the coast of Ghana, Elmina Castle is a fortified trading post that played a significant role in the transatlantic slave trade. Visitors can explore the castles dungeons and learn about the dark history of the slave trade while taking in panoramic views of the Atlantic Ocean.',
        location: 'Elmina',
        region: 'Central Region',
        price: '50',
        image: elmina,

    },
    {
        id: '1',
        name: 'CapeCoast Castle',
        description: "Located in the Central Region, Cape Coast Castle is a significant historical site and a UNESCO World Heritage Site. It played a major role in the transatlantic slave trade and is now a museum that provides insights into Ghana's colonial past.",
        location: 'CapeCoast',
        region: 'Central Region',
        price: 75,
        image: wallpaper,

    },

    {
        id: '3',
        name: 'Laraganga Mosque',
        description: 'Located in the Northern Region, Larabanga Mosque is one of the oldest mosques in West Africa. It is an architectural marvel and an important pilgrimage site for Muslims. Visitors can explore the mosque and witness the blend of traditional Sudano-Sahelian and Islamic architectural styles.',
        location: 'Larabanga',
        region: 'Northern Region',
        price: '350',
        image: larabanga,
    },

    {
        id: '4',
        name: 'Kwame Nkrumah Mausoleum',
        description: 'Situated in the capital city of Accra, the Kwame Nkrumah Mausoleum is a memorial park dedicated to Ghanas first president and the father of the countrys independence. The mausoleum houses his final resting place and exhibits on his life, offering insights into Ghanas struggle for independence.',
        location: 'Accra',
        region: 'Greater Accra',
        price: '100',
        image: tour,
    },
    {
        id: '31',
        name: 'Kakum National Park',
        description: "Situated in the coastal rainforest region of Ghana, Kakum National Park is renowned for its incredible canopy walkway, which offers visitors a thrilling treetop view. The park is also home to diverse wildlife and provides opportunities for nature walks and birdwatching.",
        location: 'CapeCoast',
        region: 'Central Region',
        price: '75',
        image: kp2,

    },
    {
        id: '5',
        name: 'Boti Falls',
        description: 'Located in the Eastern Region, Boti Falls is a beautiful cascade nestled amidst a scenic landscape. Visitors can enjoy the picturesque surroundings, take a dip in the pool, and explore the nearby Umbrella Rock, which offers stunning views of the waterfall and the surrounding area.',
        location: 'Boti',
        region: 'Eastern Region',
        price: '120',
        image: boti2,
    },
    {
        id: '8',
        name: 'Mole National Park',
        description: 'Located in the northern part of Ghana, Mole National Park is the countrys largest wildlife refuge. It offers an exceptional safari experience, with chances to spot elephants, antelopes, baboons, and various bird species. Guided tours and accommodation facilities are available for visitors.',
        location: 'Damongo',
        region: 'Northern Region',
        price: '50',
        image: moles,
    },
    {
        id: '9',
        name: 'Nzulezu  Stilt Village',
        description: 'Situated in the western part of Ghana, Nzulezo is a unique village built entirely on stilts above Lake Tadane. It offers a fascinating glimpse into the traditional lifestyle of the local people, and visitors can take boat tours to explore the village and its surroundings.',
        location: 'Beyin',
        region: 'Western Region',
        price: '100',
        image: nzulezuEdit,
    },
    {
        id: '12',
        name: 'Aburi Botanical Gardens',
        description: 'Situated in the Eastern Region, the Aburi Botanical Gardens offer a peaceful and picturesque retreat. Visitors can stroll through beautifully landscaped gardens, enjoy the vibrant flora, and admire the exotic plant species.',
        location: 'Aburi',
        region: 'Eastern Region',
        price: '100',
        image: aburi,
    },
    {
        id: '13',
        name: 'Shai Hills Resource Reserve',
        description: 'Situated near Accra, the Shai Hills Resource Reserve is a wildlife and nature reserve known for its dramatic rock formations and diverse wildlife. Visitors can spot antelopes, baboons, and various bird species while exploring the parks hiking trails and enjoying panoramic views.',
        location: 'Shai Hills',
        region: 'Eastern Region',
        price: '100',
        image: shai,
    },
    {
        id: '14',
        name: 'Kane Kwei Carpentry Workshop',
        description: 'Located in Accra, the Kane Kwei Carpentry Workshop is renowned for its unique and colorful coffins. The workshop creates custom-made coffins in various shapes and designs, reflecting the interests and professions of the deceased. It offers visitors a fascinating glimpse into Ghanas vibrant funeral traditions and craftsmanship.',
        location: 'Teshie',
        region: 'Greater Region',
        price: '100',
        image: carpenter,
    }, {
        id: '15',
        name: 'Lake Bosomtwi',
        description: 'Situated in the Ashanti Region, Lake Bosomtwi is a natural crater lake surrounded by lush green hills. It is considered a sacred lake by the local Ashanti people. Visitors can relax on the shores, swim in the clean waters, and take boat trips to explore the lake and its serene atmosphere.',
        location: 'Kumasi',
        region: 'Ashanti Region',
        price: '100',
        image: bosomtwi1,
    }, {
        id: '16',
        name: 'Kumasi Zoo',
        description: ' Located in Kumasi, the Kumasi Zoo is a popular attraction that houses a variety of wildlife species. Visitors can see lions, crocodiles, monkeys, birds, and other animals up close. The zoo also offers educational programs and guided tours to learn about the conservation efforts and biodiversity of Ghana.',
        location: 'Kumasi',
        region: 'Ashanti Region',
        price: '100',
        image: kumasi,
    }, {
        id: '17',
        name: 'Mount Afadjato',
        description: ' Situated in the Volta Region, Mount Afadjato is the highest peak in Ghana, standing at an elevation of approximately 885 meters. It offers adventurous hiking trails through lush forests and provides stunning panoramic views of the surrounding landscapes. Climbing Mount Afadjato is a popular activity for nature lovers and outdoor enthusiasts.',
        location: 'Hohoe',
        region: 'Volta Region',
        price: '100',
        image: afadjato,
    }, {
        id: '18',
        name: 'Adomi Bridge',
        description: 'Spanning the Volta River near Akosombo, the Adomi Bridge is a magnificent structure and an iconic symbol of Ghana. The bridge offers stunning panoramic views of the river and its surroundings. Visitors can walk or drive across the bridge, immersing themselves in the beauty of the Volta region.',
        location: 'Atimpoku',
        region: 'Eastern Region',
        price: '100',
        image: adomi,
    }, {
        id: '19',
        name: 'Akosombo Dam',
        description: 'Located on the Volta River, the Akosombo Dam is a monumental hydroelectric dam and a major source of Ghanas electricity. The dam created Lake Volta, the largest man-made lake in Africa. Visitors can take guided tours to learn about the dams construction, its impact on Ghanas energy production, and enjoy scenic views of the vast lake.',
        location: 'Akosombo',
        region: 'Eastern Region',
        price: '100',
        image: dam,
    }, {
        id: '20',
        name: 'Manhyia Palace Museum',
        description: 'Located in Kumasi, the Manhyia Palace Museum is a cultural heritage site that was once the residence of the Ashanti king. It showcases artifacts, regalia, and historical exhibits that provide insights into the rich Ashanti culture and history. Guided tours offer a deeper understanding of the Ashanti kingdom and its traditions.',
        location: 'Kumasi',
        region: 'Ashanti Region',
        price: '100',
        image: manhyia,
    }, {
        id: '21',
        name: 'Okomfo Anokye Sword Site',
        description: ' Situated in Kumasi, the Okomfo Anokye Sword Site is a historical and cultural landmark. It marks the spot where the legendary Ashanti priest Okomfo Anokye drove a sword into the ground, which has remained firmly fixed for centuries. The site is considered sacred, and it holds significance in the Ashanti cultural and spiritual beliefs.',
        location: 'Kumasi',
        region: 'Ashanti Region',
        price: '100',
        image: anokye,
    }, {
        id: '22',
        name: 'National Museum of Ghana',
        description: ' Situated in Accra, the National Museum of Ghana showcases the rich cultural heritage and history of the country. The museum houses a vast collection of artifacts, including archaeological finds, traditional crafts, and exhibits on Ghanaian traditions and folklore. Visitors can explore the diverse exhibits and gain a deeper understanding of Ghanas cultural tapestry.',
        location: 'Accra',
        region: 'Greater Region',
        price: '100',
        image: natmauso,
    },
    {
        id: '11',
        name: 'Wli Falls',
        description: 'Located in the Volta Region, Wli Waterfalls is the highest waterfall in West Africa, surrounded by lush greenery. Visitors can enjoy a hike through the forest to reach the falls and take a refreshing dip in the pool below. The area is also home to diverse bird species.',
        location: 'Hohoe',
        region: 'Volta Region',
        price: '100',
        image: wlifalls,
    },
    {
        id: '6',
        name: 'Jamestown Lighthouse',
        description: 'Located in the historic neighborhood of Jamestown in Accra, the Jamestown Lighthouse is a notable landmark with historical significance. Visitors can climb to the top of the lighthouse for breathtaking views of the Atlantic Ocean and the surrounding area. Jamestown itself is a vibrant and lively community, rich in history and cultural traditions.',
        location: 'Accra',
        region: 'Greater Accra',
        price: '75',
        image: lighthouse,
    },
    {
        id: '7',
        name: 'National Theater',
        description: 'Situated in Accra, the National Theatre is an architectural marvel and a hub for the performing arts in Ghana. The theater hosts various cultural performances, including music, dance, theater, and concerts. Its distinctive design, inspired by traditional African motifs, makes it a cultural and artistic landmark in the city.',
        location: 'Accra',
        region: 'Greater Accra',
        price: '250',
        image: Nationaltheater,
    },
    {
        id: '10',
        name: 'Center For National Culture (Arts Center)',
        description: 'Located in Accra, the Center for National Culture, also known as the Arts Center, is a vibrant marketplace for traditional Ghanaian crafts, artworks, and textiles. Visitors can browse through the numerous stalls and shops to find unique handmade products, including jewelry, sculptures, clothing, and traditional artifacts.',
        location: 'Accra',
        region: 'Greater Accra',
        price: '100',
        image: natmauso,
    },
    {
        id: '32',
        name: 'Lake Volta',
        description: 'As the largest man-made lake in Africa and the world, Lake Volta is an impressive sight to behold. Located in the eastern part of Ghana, it offers opportunities for fishing, boating, and relaxing by the lakeside. The surrounding landscapes are picturesque and perfect for nature enthusiasts.',
        location: 'Kumasi',
        region: 'Ashanti Region',
        price: '100',
        image: manhyia,
    },

    {
        id: '23',
        name: 'Osu Castle',
        description: 'Situated in Accra, the Osu Castle, also known as Fort Christiansborg, is a historic fortification with a complex history. It served as the seat of government and residence of colonial governors and later the presidents of Ghana. Visitors can explore the castle and learn about its role in Ghanas history, colonialism, and independence struggle.',
        location: 'Osu',
        region: 'Greater Accra',
        price: '100',
        image: osuCastle,
    }, {
        id: '24',
        name: 'Legon Botanical Gardens',
        description: 'Located in Accra, the Legon Botanical Gardens provide a tranquil escape from the bustling city. The gardens offer lush greenery, scenic walking trails, and beautiful flora. Visitors can enjoy picnics, leisurely walks, and admire the diverse plant species. The gardens also host events and recreational activities.',
        location: 'Accra',
        region: 'Greater Accra',
        price: '100',
        image: legonGardens,
    }, {
        id: '25',
        name: 'Bojo Beach',
        description: 'Located near Accra, Bojo Beach is a picturesque and serene coastal destination. The beach boasts pristine sands, clear turquoise waters, and swaying palm trees. Visitors can relax on the shores, swim in the refreshing waters, and indulge in beachfront amenities such as restaurants and beach bars.',
        location: 'Accra',
        region: 'Greater Accra',
        price: '100',
        image: bojo,
    }, {
        id: '26',
        name: 'Accra Zoo',
        description: 'Situated in Accra, the Accra Zoo is a small but charming zoo that houses a variety of animals, including monkeys, lions, crocodiles, and exotic birds. Visitors can explore the zoo and learn about the native and exotic wildlife of Ghana. The zoo provides an educational and interactive experience for both children and adults.',
        location: 'Accra',
        region: 'Greater Accra',
        price: '100',
        image: accraZoo,
    }, {
        id: '27',
        name: 'Assin Manso Slave River',
        description: 'Assin Manso, located in the Central Region, was a significant slave market during the transatlantic slave trade. Today, visitors can visit the Slave River, where captured Africans took their last bath before being sold, and learn about the history and legacy of slavery',
        location: '',
        region: 'Greater Accra',
        price: '100',
        image: slaveRiver,
    }, {
        id: '28',
        name: 'Tafe Atome Monkey Sanctuary',
        description: 'Found in the Volta Region, this sanctuary protects the endangered population of Mona monkeys. Nestled in the Volta Region of Ghana, the Tafi Monkey Sanctuary is a protected area that provides a safe haven for the endangered Mona and Patas monkey species. This community-led conservation project aims to preserve the natural habitat of these primates and promote sustainable tourism. Visitors can take guided tours, interact with the monkeys, and learn about the cultural significance of these animals to the local community.',
        location: 'Hohoe',
        region: 'Volta Accra',
        price: '100',
        image: monkey,
    }, {
        id: '29',
        name: 'Bobowasi Island',
        description: 'Located on the Volta River, Bobowasi Island is a hidden gem that offers a tranquil retreat amidst natures splendor. Accessible by boat, this serene island is a haven for those seeking a peaceful escape.The island is covered in lush vegetation, including tall palm trees, dense forests, and vibrant tropical flowers. Its untouched beauty and remote location make it an ideal destination for nature lovers, birdwatchers, and eco-tourists. Visitors can take leisurely walks along the winding trails, immersing themselves in the islands natural wonders.',
        location: 'Axim',
        region: 'Western Accra',
        price: '100',
        image: island,
    },
    {
        id: '30',
        name: 'Paga Crocodile Pond',
        description: 'In the Upper East Region of Ghana, the Paga Crocodile Pond offers a unique opportunity to get up close and personal with live crocodiles. The local community has developed a remarkable relationship with these reptiles, allowing visitors to touch and take photos with them under controlled conditions.',
        location: 'Paga',
        region: 'Northern Accra',
        price: '100',
        image: paga,
    },


]
export default data;
